# NaruMa — Catppuccin Mocha colors (Hyprland)

$base        = rgb(1e1e2e)
$mantle      = rgb(181825)
$crust       = rgb(11111b)
$text        = rgb(cdd6f4)
$subtext1    = rgb(bac2de)
$overlay1    = rgb(7f849c)
$surface0    = rgb(313244)
$surface1    = rgb(45475a)
$blue        = rgb(89b4fa)
$lavender    = rgb(b4befe)
$green       = rgb(a6e3a1)
$teal        = rgb(94e2d5)
$mauve       = rgb(cba6f7)
$red         = rgb(f38ba8)
$peach       = rgb(fab387)
$yellow      = rgb(f9e2af)

$activeBorder   = rgba(89b4faee) rgba(94e2d5ee) 45deg
$inactiveBorder = rgba(45475aaa)
$shadowColor    = rgba(11111bee)
