# NaruMa — Hyprland config
# Inspired by Omarchy (https://github.com/basecamp/omarchy)

source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/rules.conf

# Override monitors in monitors.conf (auto by default)
source = ~/.config/hypr/monitors.conf
